187651915 serialize fire event
concord-consortium/forestfire pull request #51
Opened 2024-06-13 14:07 UTC by eireland

Serializes fire events so when user scrubs back on timeline, sparks and current condition inputs are shown.

2024-06-13 15:15 UTC, pjanik requested changes
Looks good, but I can see two issues.

Minor: While playing with that, I can still see sparks from the first fire event that occurred before this one.

Major, more conceptual: Do we actually want this feature in its current form? When I wrote the original PT story, the idea was to re-apply the fire events when the model was recalculating. In this case, I find it quite strange to show sparks for so many years, as sparks only make sense in the context of the fire event, which is very short (weeks, not years). Is that what the project team requested indeed?

2024-06-27 20:17 UTC, eireland commented
This branch now also includes features requests in these stories:
[#187832506](https://www.pivotaltracker.com/story/show/187832506) - increase snapshot interval to 3 years
[#187832534](https://www.pivotaltracker.com/story/show/187832534) - Skip snapshots if the state of the landscape hasn't changed
[#187832518](https://www.pivotaltracker.com/story/show/187832518) - Add a snapshot for the end of a fire event to show the burnt areas with the spark markers.

This also has bug fixes for:
- Restoring Fire History view on time line scrubbing.
- Restarting fire event if it's been paused and timeline has been scrubbed.

2024-07-31 13:16 UTC, pjanik commented
All my comments have been addressed by @eireland and myself as part of the work on https://github.com/concord-consortium/forestfire/pull/59. Hence, I am merging this PR into the main branch.

2024-07-31 13:16 UTC, pjanik approved these changes

2024-07-31 13:16 UTC, merged